app.controller('epicSpell', function($scope) {
  $scope.seeds = {
    afflict: {
      code: 'afflict',
      name: 'Afflict',
      school: 'Enchantment',
      subschool: 'Compulsion',
      descriptor: 'Fear, Mind-Affecting',
      dc: 14,
      v: true,
      s: true,
      df: false,
      ct: '1 st action',
      range: '300 ft',
      target: 'One creature',
      dismiss: false,
      duration: '20 min',
      saving_throw: 'Will',
      st_effect: 'Negates',
      speel_resist: true,
      harmless: null,
      link: 'http://www.d20srd.org/srd/epic/seeds/afflict.htm'
    },
    animate: {
      code: 'animate',
      name: 'Animate',
      school: 'Transmutation',
      subschool: 'null',
      descriptor: 'null',
      dc: 25,
      v: true,
      s: true,
      df: false,
      ct: '1 min',
      range: '300 ft',
      target: '30 ft³ matter',
      dismiss: false,
      duration: '20 rounds',
      saving_throw: 'None',
      st_effect: 'null',
      speel_resist: false,
      harmless: null,
      link: 'http://www.d20srd.org/srd/epic/seeds/animate.htm'
    },
    animateDead: {
      code: 'animateDead',
      name: 'Animate Dead',
      school: 'Necromancy',
      subschool: 'null',
      descriptor: 'Evil',
      dc: 23,
      v: true,
      s: true,
      df: false,
      ct: '1 min',
      range: 'Touch',
      target: 'Corpse',
      dismiss: false,
      duration: 'Instantaneous',
      saving_throw: 'None',
      st_effect: 'null',
      speel_resist: false,
      harmless: null,
      link: 'http://www.d20srd.org/srd/epic/seeds/animateDead.htm'
    },
    armor: {
      code: 'armor',
      name: 'Armor',
      school: 'Conjuration',
      subschool: 'Creation',
      descriptor: 'Force',
      dc: 14,
      v: true,
      s: true,
      df: false,
      ct: '1 min',
      range: 'Touch',
      target: 'Creature',
      dismiss: true,
      duration: '24 h',
      saving_throw: 'Will',
      st_effect: 'Negates',
      speel_resist: true,
      harmless: true,
      link: 'http://www.d20srd.org/srd/epic/seeds/armor.htm'
    },
    banish: {
      code: 'banish',
      name: 'Banish',
      school: 'Abjuration',
      subschool: 'null',
      descriptor: 'null',
      dc: 27,
      v: true,
      s: true,
      df: false,
      ct: '1 min',
      range: '75 ft',
      target: 'Extraplanar creature',
      dismiss: false,
      duration: 'Instantaneous',
      saving_throw: 'Will',
      st_effect: 'Negates',
      speel_resist: true,
      harmless: null,
      link: 'http://www.d20srd.org/srd/epic/seeds/banish.htm'
    },
    compel: {
      code: 'compel',
      name: 'Compel',
      school: 'Enchantment',
      subschool: 'Compulsion',
      descriptor: 'Mind-Affecting',
      dc: 19,
      v: true,
      s: true,
      df: false,
      ct: '1 min',
      range: '75 ft',
      target: 'Creature',
      dismiss: false,
      duration: '20 h',
      saving_throw: 'Will',
      st_effect: 'Negates',
      speel_resist: true,
      harmless: null,
      link: 'http://www.d20srd.org/srd/epic/seeds/compel.htm'
    },
    conceal: {
      code: 'conceal',
      name: 'Conceal',
      school: 'Illusion',
      subschool: 'Glamer',
      descriptor: 'null',
      dc: 17,
      v: true,
      s: true,
      df: false,
      ct: '1 min',
      range: 'Touch',
      target: 'Creature',
      dismiss: true,
      duration: '200 min',
      saving_throw: 'Will',
      st_effect: 'Negates',
      speel_resist: true,
      harmless: null,
      link: 'http://www.d20srd.org/srd/epic/seeds/conceal.htm'
    },
    conjure: {
      code: 'conjure',
      name: 'Conjure',
      school: 'Conjuration',
      subschool: 'Creation',
      descriptor: 'null',
      dc: 21,
      v: true,
      s: true,
      df: false,
      ct: '1 min',
      range: '0 ft',
      target: '20 ft³ matter',
      dismiss: false,
      duration: '8 h',
      saving_throw: 'None',
      st_effect: 'null',
      speel_resist: false,
      harmless: null,
      link: 'http://www.d20srd.org/srd/epic/seeds/conjure.htm'
    },
    contact: {
      code: 'contact',
      name: 'Contact',
      school: 'Divination',
      subschool: 'null',
      descriptor: 'null',
      dc: 23,
      v: true,
      s: true,
      df: false,
      ct: '1 min',
      range: 'null',
      target: 'One creature',
      dismiss: false,
      duration: '200 min',
      saving_throw: 'None',
      st_effect: 'null',
      speel_resist: false,
      harmless: null,
      link: 'http://www.d20srd.org/srd/epic/seeds/contact.htm'
    },
    delude: {
      code: 'delude',
      name: 'Delude',
      school: 'Illusion',
      subschool: 'Figment',
      descriptor: 'null',
      dc: 14,
      v: true,
      s: true,
      df: false,
      ct: '1 min',
      range: '12.000 ft',
      target: 'null',
      dismiss: false,
      duration: 'Concentratio + 20 h',
      saving_throw: 'Will',
      st_effect: 'Disbelief',
      speel_resist: false,
      harmless: null,
      link: 'http://www.d20srd.org/srd/epic/seeds/delude.htm'
    },
    destroy: {
      code: 'destroy',
      name: 'Destroy',
      school: 'Transmutation',
      subschool: 'null',
      descriptor: 'null',
      dc: 29,
      v: true,
      s: true,
      df: false,
      ct: '1 min',
      range: '12.000 ft',
      target: 'One creature',
      dismiss: false,
      duration: 'Instantaneous',
      saving_throw: 'Fortitude',
      st_effect: 'Half',
      speel_resist: true,
      harmless: null,
      link: 'http://www.d20srd.org/srd/epic/seeds/destroy.htm'
    },
    dispel: {
      code: 'dispel',
      name: 'Dispel',
      school: 'Abjuration',
      subschool: 'null',
      descriptor: 'null',
      dc: 19,
      v: true,
      s: true,
      df: false,
      ct: '1 min',
      range: '300 ft',
      target: 'One target',
      dismiss: false,
      duration: 'Instantaneous',
      saving_throw: 'None',
      st_effect: 'null',
      speel_resist: false,
      harmless: null,
      link: 'http://www.d20srd.org/srd/epic/seeds/dispel.htm'
    },
    energy: {
      code: 'energy',
      name: 'Energy',
      school: 'Evocation',
      subschool: 'null',
      descriptor: 'Acid, Fire, Electricity, Cold or Sonic',
      dc: 19,
      v: true,
      s: true,
      df: false,
      ct: '1 min',
      range: '300 ft',
      target: 'Area',
      dismiss: false,
      duration: 'Instantaneous',
      saving_throw: 'Reflex',
      st_effect: 'Half',
      speel_resist: true,
      harmless: null,
      link: 'http://www.d20srd.org/srd/epic/seeds/energy.htm'
    },
    foresee: {
      code: 'foresee',
      name: 'Foresee',
      school: 'Divination',
      subschool: 'null',
      descriptor: 'null',
      dc: 17,
      v: true,
      s: true,
      df: false,
      ct: '1 min',
      range: 'Personal',
      target: 'You',
      dismiss: false,
      duration: 'Instantaneous',
      saving_throw: 'None',
      st_effect: 'null',
      speel_resist: false,
      harmless: null,
      link: 'http://www.d20srd.org/srd/epic/seeds/foresee.htm'
    },
    fortify: {
      code: 'fortify',
      name: 'Fortify',
      school: 'Transmutation',
      subschool: 'null',
      descriptor: 'null',
      dc: 17,
      v: true,
      s: true,
      df: false,
      ct: '1 min',
      range: 'Touch',
      target: 'One creature',
      dismiss: false,
      duration: '20 h',
      saving_throw: 'Will',
      st_effect: 'Negates',
      speel_resist: true,
      harmless: true,
      link: 'http://www.d20srd.org/srd/epic/seeds/fortify.htm'
    },
    heal: {
      code: 'heal',
      name: 'Heal',
      school: 'Conjuration',
      subschool: 'Healing',
      descriptor: 'null',
      dc: 25,
      v: true,
      s: true,
      df: true,
      ct: '1 min',
      range: 'Touch',
      target: 'One creature',
      dismiss: false,
      duration: 'Instantaneous',
      saving_throw: 'Fortitude',
      st_effect: 'Partial',
      speel_resist: true,
      harmless: true,
      link: 'http://www.d20srd.org/srd/epic/seeds/heal.htm'
    },
    life: {
      code: 'life',
      name: 'Life',
      school: 'Conjuration',
      subschool: 'Healing',
      descriptor: 'null',
      dc: 27,
      v: true,
      s: true,
      df: true,
      ct: '1 min',
      range: 'Touch',
      target: 'Dead creature',
      dismiss: false,
      duration: 'Instantaneous',
      saving_throw: 'None',
      st_effect: 'null',
      speel_resist: true,
      harmless: true,
      link: 'http://www.d20srd.org/srd/epic/seeds/life.htm'
    },
    reflect: {
      code: 'reflect',
      name: 'Reflect',
      school: 'Abjuration',
      subschool: 'null',
      descriptor: 'null',
      dc: 27,
      v: true,
      s: true,
      df: false,
      ct: '1 min',
      range: 'Personal',
      target: 'You',
      dismiss: false,
      duration: '12 h',
      saving_throw: 'None',
      st_effect: 'null',
      speel_resist: false,
      harmless: null,
      link: 'http://www.d20srd.org/srd/epic/seeds/reflect.htm'
    },
    reveal: {
      code: 'reveal',
      name: 'Reveal',
      school: 'Divination',
      subschool: 'null',
      descriptor: 'null',
      dc: 19,
      v: true,
      s: true,
      df: false,
      ct: '1 min',
      range: 'null',
      target: 'null',
      dismiss: true,
      duration: '20 min',
      saving_throw: 'None',
      st_effect: 'null',
      speel_resist: false,
      harmless: null,
      link: 'http://www.d20srd.org/srd/epic/seeds/reveal.htm'
    },
    slay: {
      code: 'slay',
      name: 'Slay',
      school: 'Necromancy',
      subschool: 'null',
      descriptor: 'Death',
      dc: 25,
      v: true,
      s: true,
      df: false,
      ct: '1 min',
      range: '300 ft',
      target: 'One living creature',
      dismiss: false,
      duration: 'Instantaneous',
      saving_throw: 'Fortitude',
      st_effect: 'Partial',
      speel_resist: true,
      harmless: null,
      link: 'http://www.d20srd.org/srd/epic/seeds/slay.htm'
    },
    summon: {
      code: 'summon',
      name: 'Summon',
      school: 'Conjuration',
      subschool: 'Summoning',
      descriptor: 'null',
      dc: 14,
      v: true,
      s: true,
      df: false,
      ct: '1 min',
      range: '75 ft',
      target: 'null',
      dismiss: true,
      duration: '20 rounds',
      saving_throw: 'Will',
      st_effect: 'Negates',
      speel_resist: true,
      harmless: null,
      link: 'http://www.d20srd.org/srd/epic/seeds/summon.htm'
    },
    transform: {
      code: 'transform',
      name: 'Transform',
      school: 'Transmutation',
      subschool: 'null',
      descriptor: 'null',
      dc: 21,
      v: true,
      s: true,
      df: false,
      ct: '1 min',
      range: '300 ft',
      target: 'One creature',
      dismiss: false,
      duration: 'Permanent',
      saving_throw: 'Fortitude',
      st_effect: 'Negates',
      speel_resist: true,
      harmless: null,
      link: 'http://www.d20srd.org/srd/epic/seeds/transform.htm'
    },
    transport: {
      code: 'transport',
      name: 'Transport',
      school: 'Conjuration',
      subschool: 'null',
      descriptor: 'Teleportation',
      dc: 27,
      v: true,
      s: true,
      df: false,
      ct: '1 min',
      range: 'Touch',
      target: 'Creature',
      dismiss: false,
      duration: 'Instantaneous',
      saving_throw: 'Will',
      st_effect: 'Negates',
      speel_resist: true,
      harmless: null,
      link: 'http://www.d20srd.org/srd/epic/seeds/transport.htm'
    },
    ward: {
      code: 'ward',
      name: 'Ward',
      school: 'Abjuration',
      subschool: 'null',
      descriptor: 'null',
      dc: 14,
      v: true,
      s: true,
      df: false,
      ct: '1 min',
      range: 'Touch',
      target: 'Creature',
      dismiss: false,
      duration: '24 h',
      saving_throw: 'None',
      st_effect: 'null',
      speel_resist: true,
      harmless: null,
      link: 'http://www.d20srd.org/srd/epic/seeds/ward.htm'
    }
  };

  $scope.seedList     = {};
  $scope.mainSeedList = {};
  $scope.mySeeds      = [];
  $scope.dc           = 0;
  $scope.spellType    = "Arcane";
  $scope.mainSeed     = "";

  $scope.$watch('seedList', function(newVal, oldVal, scope) {
    scope.mySeeds = {};
    scope.dc      = 0;

    for(var sood in newVal) {
      if(newVal[sood]) {
        scope.dc += scope.seeds[sood].dc;
        scope.mySeeds[scope.seeds[sood].code] = scope.seeds[sood];
      }
    }
  }, true); // Setting `objectEquality` to `true` is important do to the fact that Angular's falsey doesn't throw for this watching.
  $scope.$watch('mainSeedList', function(newVal, oldVal, scope) {
    scope.mainSeed = "";
    
    for(var sood in newVal) {
      if(newVal[sood]) {
        scope.mainSeed = sood;
        break;
      }
    }
  }, true);
  $scope.$watch('type', function(newVal, oldVal, scope) {
    if(newVal) { scope.spellType = "Divine"; }
    else { scope.spellType = "Arcane"; }
  });
});
